NOM = j_window
EXT = .c
CXX = gcc
INCL = -IE:\_CLOUDAPPS\devel\n++C\_TOOLS\_MINGW\japi\include
LIBS = -LE:\_CLOUDAPPS\devel\n++C\_TOOLS\_MINGW\japi\lib -ljapi -lwsock32
RES = 
COP = -std=c99 -O2 -Wall -Wextra

$(NOM).exe: $(NOM)$(EXT)
	$(CXX) $(COP) -o $(NOM).exe $(NOM)$(EXT) $(RES) $(INCL) $(LIBS)
	
clean:
	del *.o
